# Generated by Django 2.2 on 2019-10-09 18:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
                ('pos', models.SmallIntegerField(
                    default='0', verbose_name='position')),
                ('rejectable', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
                'ordering': ['pos'],
            },
        ),
        migrations.CreateModel(
            name='PositionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('apply_date', models.DateTimeField(blank=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                         related_name='positionapplication_application_status', to='positionapps.ApplicationStatus')),
                ('company_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                     related_name='positionapplication_company', to='company.Company')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='positionapplication_position', to='position.JobPosition')),
                ('created_date', models.DateTimeField(
                    blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(
                    blank=True, default=django.utils.timezone.now)),
                ('application_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                         related_name='statushistory_application_status', to='positionapps.ApplicationStatus')),
                ('pos_app', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.CASCADE, to='positionapps.PositionApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('linkedin_url', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(
                    blank=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(
                    blank=True, default=django.utils.timezone.now, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='contact_company', to='company.Company')),
                ('pos_app', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positionapps.PositionApplication')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='contact_position', to='position.JobPosition'))
            ],
        ),
        migrations.CreateModel(
            name='PositionApplicationNote',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(
                    blank=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(
                    blank=True, default=django.utils.timezone.now, null=True)),
                ('pos_app', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.CASCADE, to='positionapps.PositionApplication')),
            ],
        )
    ]
