# Generated by Django 2.2.5 on 2019-11-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positionapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_position', to='position.PositionDetail'),
        ),
        migrations.RemoveField(
            model_name='positionapplication',
            name='position',
        ),
        migrations.AddField(
            model_name='positionapplication',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionapplication_position', to='position.PositionDetail'),
        ),
    ]
