# Generated by Django 2.2.5 on 2019-11-26 03:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('positionapps', '0002_auto_20191123_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(blank=True, max_length=50, null=True)),
                ('interview_round', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pos_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positionapps.PositionApplication')),
            ],
        ),
    ]
