# Generated by Django 2.2 on 2019-10-15 19:30

from django.db import migrations, models
import uuid
from django.core.files import File
from urllib.request import urlretrieve
from urllib.error import HTTPError
import os


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191014_2316'),
    ]

    def migrate_data(apps, schema_editor):
        Company = apps.get_model('company', 'Company')
        companies = Company.objects.all()
        for company in companies:
            if company.cb_company_logo is not None and company.cb_company_logo is not '':
                try:
                    urlretrieve(company.cb_company_logo, filename=company.cb_company_logo.split('/')[-1])
                    file = open(company.cb_company_logo.split('/')[-1], 'rb')
                    filename = "%s.%s" % (uuid.uuid4(), 'jpg')
                    company.logo.save(filename, File(file), save=True)
                    company.save()
                    os.remove(company.cb_company_logo.split('/')[-1])
                except FileNotFoundError as err:
                    pass  # something wrong with local path
                except HTTPError as err:
                    pass  # something wrong with url
            elif company.company_logo is not None and company.company_logo is not '':
                try:
                    urlretrieve(company.company_logo, filename=company.company_logo.split('/')[-1])
                    file = open(company.company_logo.split('/')[-1], 'rb')
                    filename = "%s.%s" % (uuid.uuid4(), 'jpg')
                    company.logo.save(filename, File(file), save=True)
                    company.save()
                    os.remove(company.company_logo.split('/')[-1])
                except FileNotFoundError as err:
                    pass  # something wrong with local path
                except HTTPError as err:
                    pass  # something wrong with url

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cb_domain',
            new_name='domain',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(default='8af3c0b7-6f12-4d54-8d64-5c49f40f28fb.png', upload_to=''),
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
    ]
