# Generated by Django 2.2 on 2019-10-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20191021_2237'),
    ]

    def fix_data(apps, schema_editor):
        Company = apps.get_model('company', 'Company')
        companies = Company.objects.all()
        for company in companies:
            if company.logo.name.startswith('settings'):
                company.logo.name = '8af3c0b7-6f12-4d54-8d64-5c49f40f28fb.png'
                company.save()


    operations = [
        migrations.RunPython(fix_data, reverse_code=migrations.RunPython.noop),
    ]
