# Generated by Django 2.2 on 2019-10-09 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import json
import urllib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def populate_data(apps, schema_editor):
        Country = apps.get_model('utils', 'Country')
        State = apps.get_model('utils', 'State')
        with urllib.request.urlopen(
                "https://raw.githubusercontent.com/stefanbinder/countries-states/master/countries.json") as json_file:
            data = json.load(json_file)
            for d in data:
                code2 = d['code2']
                code3 = d['code3']
                name = d['name']
                capital = d['capital']
                region = d['region']
                subregion = d['subregion']
                country = Country.objects.create(code2=code2, code3=code3, name=name, capital=capital, region=region,
                                                 subregion=subregion)
                country.save()
                for w in d['states']:
                    code = w['code']
                    if code is None:
                        code = ''
                    name = w['name']
                    subdivision = w['subdivision']
                    if subdivision is None:
                        subdivision = ''
                    state = State.objects.create(country=country, code=code, name=name, subdivision=subdivision)
                    state.save()

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('is_html', models.BooleanField(default=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code2', models.CharField(blank=True, max_length=10)),
                ('code3', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('capital', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('subregion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='question')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
            ],
            options={
                'verbose_name': 'feedback question',
                'verbose_name_plural': 'feedback questions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('subdivision', models.CharField(blank=True, max_length=200)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='value')),
                ('custom_input', models.BooleanField(default=False, verbose_name='custom input')),
                ('pos', models.SmallIntegerField(default='0', verbose_name='position')),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='utils.FeedbackQuestion')),
            ],
            options={
                'verbose_name': 'feedback question item',
                'verbose_name_plural': 'feedback question items',
                'ordering': ['pos'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(blank=True, max_length=250, verbose_name='user input')),
                ('ip', models.GenericIPAddressField(verbose_name="user's IP")),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='utils.FeedbackQuestionItem', verbose_name='answered item')),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.FeedbackQuestion', verbose_name='feedback question')),
            ],
            options={
                'verbose_name': 'feedback answer',
                'verbose_name_plural': 'feedback answers',
            },
        ),
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop),
    ]
