# Generated by Django 2.1.7 on 2019-12-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positionapps', '0003_feedback'),
        ('cvparser', '0002_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pos_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positionapps.PositionApplication'),
        ),
    ]
