# Generated by Django 2.2 on 2019-09-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    def create_user_types(apps, schema_editor):
        UserType = apps.get_model('users', 'UserType')
        User = apps.get_model('users', 'User')
        undefined = UserType(name='Undefined')
        undefined.save()
        public = UserType(name='Public')
        public.save()
        student = UserType(name='Student')
        student.save()
        alumni = UserType(name='Alumni')
        alumni.save()
        alumni = UserType(name='Employer')
        alumni.save()

        users = User.objects.all()
        for user in users:
            if user.user_type == 0:
                user.type = undefined
            elif user.user_type == 1:
                user.type = public
            elif user.user_type == 2:
                user.type = student
            elif user.user_type == 3:
                user.type = alumni
            user.save()

    operations = [
        #migrations.RunPython(create_user_types, reverse_code=migrations.RunPython.noop)
    ]
