# Generated by Django 2.0.1 on 2019-12-21 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '__first__'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['job_title'],
            },
        ),
        migrations.CreateModel(
            name='PositionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('department', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positiondetail_company', to='company.Company')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Country')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='position.JobPosition')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.State')),
            ],
            options={
                'ordering': ['updated_date'],
            },
        ),
    ]
