# Generated by Django 2.0.1 on 2019-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiondetail',
            name='job',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
