# Generated by Django 2.2.5 on 2019-11-16 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_positiondetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiondetail',
            options={'ordering': ['updated_date']},
        ),
        migrations.AlterField(
            model_name='positiondetail',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
