# Generated by Django 2.0.1 on 2019-12-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20191220_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiondetail',
            name='job',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
